### ISSUE TITLE
What is the difference with arc-swap

### ISSUE THREAD

**Issue by incker** [colinjfw/arc-atomic#1]
Hello 👋

What is the difference with [arc-swap](https://crates.io/crates/arc-swap) ?
Thank you)

**Comment by colinjfw** [comment]
You can read about the performance characteristics of ArcSwap [here](https://docs.rs/arc-swap/1.6.0/arc_swap/docs/performance/index.html).

This crate uses a different mechanism while still providing a lock-free way to swap an Arc. The mechanism in this crate is simpler, relying on SeqCst ordering and underlying reference counts of the Arc structure to ensure that an Arc can be safely swapped. In general ArcSwap provides a cache of references so you may end up doing less atomic increments which could be beneficial in some situations. This crate may be beneficial if you find for whatever reason you cannot take advantage of the caching mechanism used by ArcSwap.
